init

diff --git a/bin/tray b/bin/tray
--- a/bin/tray
+++ b/bin/tray
@@ -36,24 +36,33 @@ then
   exit 1
 fi
 
-# Check the number of arguments
-if [ "$#" -lt 2 ]; then
-    echo "Usage: $0 <arg1> <arg2>"
-    exit 1
-fi
-
-# Access the arguments
-arg1="$1"
-arg2="$2"
-echo "Argument 1: $arg1"
-echo "Argument 2: $arg2"
-
-
 # Absolute path to this script, e.g. /home/user/bin/foo.sh
 SCRIPT=$(readlink -f "$0")
 # Absolute path this script is in, thus /home/user/bin
 SCRIPTPATH=$(dirname "$SCRIPT")
 echo $SCRIPTPATH
 
-# cd repository
-# ./gradlew clean app:run --args='audio on'
+curdir=$(pwd)
+
+
+# Check the number of arguments
+if [ "$#" -lt 1 ]; then
+    echo "Missing arguments"
+    echo "Usage: tray <arg1> <arg2>"
+    exit 1
+fi
+
+if [ "$#" -eq 1 ]; then
+    cd ${SCRIPTPATH}/../repository
+    ./gradlew clean app:run --args="$1"
+    cd ${curdir}
+elif [ "$#" -eq 2 ]; then
+    cd ${SCRIPTPATH}/../repository
+    ./gradlew clean app:run --args="$1 $2"
+    cd ${curdir}
+else
+    echo "Too many arguments"
+    echo "Usage: tray <arg1> <arg2>"
+    exit 1
+fi
+
