init

diff --git a/bin/tray b/bin/tray
--- a/bin/tray
+++ b/bin/tray
@@ -6,7 +6,7 @@ set -u
 # shellcheck disable=SC2292
 if [ -z "${BASH_VERSION:-}" ]
 then
-  echo "Error: Bash is required to run brew." >&2
+  echo "Error: Bash is required to run tray." >&2
   exit 1
 fi
 
@@ -15,24 +15,24 @@ set +o posix # as we are using bash now
 # Fail fast with concise messages when PWD has issues
 if [[ -z "${PWD-}" ]]
 then
-  echo "Error: \$PWD must be set to run brew." >&2
+  echo "Error: \$PWD must be set to run tray." >&2
   exit 1
 fi
 if ! [[ -d "${PWD}" ]]
 then
-  echo "Error: The current working directory must exist to run brew." >&2
+  echo "Error: The current working directory must exist to run tray." >&2
   exit 1
 fi
 if ! [[ -r "${PWD}" ]]
 then
-  echo "Error: The current working directory must be readable to ${USER} to run brew." >&2
+  echo "Error: The current working directory must be readable to ${USER} to run tray." >&2
   exit 1
 fi
 
 # Fail fast with concise message when HOME is unset
 if [[ -z "${HOME:-}" ]]
 then
-  echo "Error: \$HOME must be set to run brew." >&2
+  echo "Error: \$HOME must be set to run tray." >&2
   exit 1
 fi
 
